### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by ShinySilver** [GabeRundlett/gvox_engine#13]
Hello,
I had an error when trying to build the engine.
From what I understand, the engine have a dependency called liblzma, as listed below:

![image](https://github.com/GabeRundlett/gvox_engine/assets/36570018/083b43c4-a970-430b-8ee9-99113c041382)

I had an error when building liblzma:

![image](https://github.com/GabeRundlett/gvox_engine/assets/36570018/b966a91a-d29d-465c-9652-87376926e0ef)

So I dug a bit deeper, tried to download the file that vcpkg failed to download, and [discovered that xy repo was disabled](https://github.com/tukaani-project/xz/archive/v5.4.3.tar.gz).

I used google, and found out that there was a backdoor in xy that was discovered yesterday. More details here: https://tukaani.org/xz-backdoor/

So for now, I guess the build is broken? And you might want to check if the version of liblzma you installed on your machine is affected ^^'

**Comment by GilanRanger** [comment]
The versions of xz that were backdoored were specifically the release tarballs of 5.6.0 and 5.6.1 (please correct me if wrong.) That means that this project is safe. 

If you want to still build while the xz GitHub is down, follow this to switch from tukaani-project to bminor:
https://github.com/microsoft/vcpkg/issues/37839

**Comment by RedNicStone** [comment]
> The versions of xz that were backdoored were specifically the release tarballs of 5.6.0 and 5.6.1 (please correct me if wrong.) That means that this project is safe.

The project is safe anyway. The back-door explicitly targeted the SSH daemon and only releases destined to be compiled into the linux kernel were maliciously modified. It was part of the kernel build system and a clean source build would never be affected.

**Comment by GabeRundlett** [comment]
I'm not sure what dep even uses lzma

**Comment by RedNicStone** [comment]
VCPKG itself uses liblzma directly in order to decompress upstream packages. Removing this dependency would fix the issue :wink:

**Comment by ShinySilver** [comment]
Thanks for the answers :) I guess I'll keep this issue open as long as xy is down, so that other users that are not on discord can find the temporary fix?

**Comment by ShinySilver** [comment]
https://github.com/tukaani-project/xz/ is back online.
