### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ShinySilver** [GabeRundlett/gvox_engine#14]
Hello again,
I have an issue when building gvox engine on linux.

In math.hpp, you include a glsl file which define a select macro. The next line, you include glm.hpp, which somehow include a header with a function called "select".
 
![image](https://github.com/GabeRundlett/gvox_engine/assets/36570018/e2085fad-4d53-471f-9fea-248824ae68a2)

This cause an compilation error.

![image](https://github.com/GabeRundlett/gvox_engine/assets/36570018/431fe073-1a0c-47a5-bc02-f67a0d57d3ae)

I was able to side step the issue on my end by exchanging line 4 and 5 of math.hpp.

**Comment by GabeRundlett** [comment]
Thank you for this issue report! I believe I have fixed it with [fe1d9cd](https://github.com/GabeRundlett/gvox_engine/commit/fe1d9cdb989da959e5b83bcf9274eee86612d3a7)
