### ISSUE TITLE
[DAXA] No Suitable Device Found During Initialization

### ISSUE THREAD

**Issue by dd123-a** [GabeRundlett/gvox_engine#17]
I am facing an issue where DAXA fails to initialize due to no suitable device being found. The error message is as follows:

深色版本
[[DAXA ASSERT FAILURE]]: error code: DAXA_RESULT_NO_SUITABLE_DEVICE_FOUND(1073741862), failed to create device.
Environment:
Operating System: Windows11
Graphics Card: mx450
Vulkan SDK Version:1.3.290.0
Steps to Reproduce:
Clone the project repository from [repository link].
Navigate to the project root directory.
Configure the project with CMake:

cmake -B .out/cl-x86_64-windows-msvc -S . -G "Ninja Multi-Config"
Build the project:

cmake --build .out/cl-x86_64-windows-msvc --config Debug
Run the resulting executable.
Expected Behavior:
DAXA should initialize successfully, and the application should run without any issues related to device creation.

Actual Behavior:
Upon running the application, I receive the error message indicating that DAXA cannot find a suitable device to initialize with.

Additional Information:
Vulkan Support Verification: My graphics card supports Vulkan, and the driver is up to date.

**Comment by dd123-a** [comment]
i can play the demo

**Comment by GabeRundlett** [comment]
Hey @dd123-a. On the master branch, the project contains hardware raytracing, which means you need to support HWRT to run the master branch. If you want the latest changes, but your card doesn't support HWRT, check-out the compute-rt branch

**Comment by dd123-a** [comment]
Hey，@GabeRundlett. I check-out the compute-rt branch and get this problem [[DAXA ASSERT FAILURE]]: error code: DAXA_RESULT_ERROR_EXTENSION_NOT_PRESENT(-7), failed to create device.

**Comment by dd123-a** [comment]
After updating the driver, I resolved the issue. I will close this

**Comment by dd123-a** [comment]
After updating the driver, I resolved the issue.
