### ISSUE TITLE
Doesn't compile under w8

### ISSUE THREAD

**Issue by USSRcoder** [GabeRundlett/gvox_engine#3]
Doesn't compile under w8 (msvc2019, no clang).
The game from the release does not start (win8) vkGetDeviceBufferMemoryRequirements there is no such function in the dll. Why are you doing this?
It didn't compile via cmake (vcpkg version error, got dxc || daxa 1.2 and need 1.0). Why are you doing this?
Spent a whole day building daxa by hand (not built without editing the code, write issue...). Why... 
Build, but still could not attach it to the game. ```daxa::initialize();``` There is no such thing as where it comes from... deleted everything...)

**Comment by GabeRundlett** [comment]
it shouldn't work with Visual Studio 2019. It doesn't have a modern enough version of CMake included, however, I haven't been using the master branch in a while

**Comment by GabeRundlett** [comment]
another issue that could be a problem with using Windows 8 is that you may not have modern enough drivers. I don't know what the driver situation is on Windows 8 and I don't really have any way of checking

**Comment by USSRcoder** [comment]
It's a pity that I couldn't run it on Windows 8. So I wanted to see how your engine works. Daxa requires win10 (...

**Comment by GabeRundlett** [comment]
Yeah I mean, I don't know what the issue would be if you tried using VS2022 or Clang+external CMake. The only other issue I could think of would be an out of date driver
