### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by BenjaminGu** [GabeRundlett/gvox_engine#7]
YouTube comments keep getting deleted, so I'm leaving it here as an issue.

I found the documentation on Daxa and was able to build it.
I tried to build gvox_engine in the same way, but the following error occurred.

================

-- Running vcpkg install
Fetching registry information from https://github.com/GabeRundlett/vcpkg-registry (HEAD)...
Error: No version entry for daxa at version nightly#50.
Available versions:
    nightly#76
    0.1.0
    0.0.1

See `vcpkg help versioning` for more information.
Error: No version entry for gvox at version nightly#32.
Available versions:
    nightly#64

**Comment by GabeRundlett** [comment]
This is a real issue, that I need to fix with my vcpkg registry... I've been lazy about it, since what you can do to fix it is just run `vcpkg x-update-baseline` in the project root. This technically can break things though, since this updates the packages, and Daxa might have breaking changes

**Comment by GabeRundlett** [comment]
Daxa shouldn't have any breaking changes, AFAIK, so this should be fine to run. If you don't want to add vcpkg to your path, you can manually update the hash inside the `vcpkg-configuration.json` to match that of the latest git hash on the registry, which is also linked in that file

**Comment by BenjaminGu** [comment]
I executed the command "vcpkg x-update-baseline" and this time I encountered the following error message.

> -- Running vcpkg install
> Fetching registry information from https://github.com/GabeRundlett/vcpkg-registry (HEAD)...
> Error: daxa:x64-windows@nightly#76 does not have required feature glslang
> 
> -- Running vcpkg install - failed
> CMake Error at D:/dev/utils/vcpkg/scripts/buildsystems/vcpkg.cmake:883 (message):
>   vcpkg install failed.  See logs for more information:
>   D:\VoxelProjects\Gabe\gvox_engine\.out\cl-x86_64-windows-msvc\vcpkg-manifest-install.log
> Call Stack (most recent call first):
>   D:/Program Files/CMake/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:124 (include)
>   CMakeLists.txt:5 (project)
> 
> 
> CMake Error: CMake was unable to find a build program corresponding to "Ninja Multi-Config".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
> -- Configuring incomplete, errors occurred!

**Comment by GabeRundlett** [comment]
Ah. I guess I haven't pushed in a while. Let me push my local changes, give me a minute...

**Comment by GabeRundlett** [comment]
I pushed. It should build now. That's my bad!!

**Comment by LinaJu** [comment]
I am sorry but I failed again.
```
-- Running vcpkg install
Fetching registry information from https://github.com/GabeRundlett/vcpkg-registry (HEAD)...
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.8) Downloading portable powershell-core 7.2.8...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.8/PowerShell-7.2.8-win-x86.zip->D:\dev\utils\vcpkg\downloads\PowerShell-7.2.8-win-x86.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.8/PowerShell-7.2.8-win-x86.zip
Extracting powershell-core...
error: while detecting compiler information:
The log file content at "D:\dev\utils\vcpkg\buildtrees\detect_compiler\stdout-x64-windows.log" is:
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "D:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/dev/utils/vcpkg/buildtrees/detect_compiler/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\dev\utils\vcpkg\buildtrees\detect_compiler\config-x64-windows-rel-CMakeCache.txt.log
      D:\dev\utils\vcpkg\buildtrees\detect_compiler\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:310 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:147 (include)



error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
-- Running vcpkg install - failed
CMake Error at D:/dev/utils/vcpkg/scripts/buildsystems/vcpkg.cmake:883 (message):
  vcpkg install failed.  See logs for more information:
  D:\bjProjects\gvox_engine\.out\cl-x86_64-windows-msvc\vcpkg-manifest-install.log
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:5 (project)


CMake Error: CMake was unable to find a build program corresponding to "Ninja Multi-Config".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
```

**Comment by GabeRundlett** [comment]
I have no clue. What's in those files?
      D:\dev\utils\vcpkg\buildtrees\detect_compiler\config-x64-windows-rel-CMakeCache.txt.log
      D:\dev\utils\vcpkg\buildtrees\detect_compiler\config-x64-windows-out.log

I would try deleting the .out folder and rebuilding from scratch.

**Comment by LinaJu** [comment]
Thank you for your prompt response.
After deleting the .out folder, I built again and the build succeeded.
But this time I got the following runtime error:

`The procedure entry point vkCmdEndRendering could not be located in the dynamic link library .out\cl-x86_64-windows-msvc\Debug\gabe_voxel_game.exe`

I'm using version 1.3.236 of the Vulkan SDK and other projects are working fine.

**Comment by GabeRundlett** [comment]
That is an insane error, I have never seen that before. What GPU do you have? Sorry for the late response, I'm just waking up now

**Comment by LinaJu** [comment]
I tested on 1050 and 2060 super and the results were the same for both graphics cards.

**Comment by GabeRundlett** [comment]
when is the last time you updated your drivers?

**Comment by LinaJu** [comment]
I had tested with the latest version 528.34.
I only removed the display driver and reinstalled the same version.
Then gvox_engine just worked.
What a weird situation!

**Comment by GabeRundlett** [comment]
Alright, I'm glad it worked.. I wonder what was wrong with your driver before... I'm going to close this now
